<?php
require_once __DIR__.'/../../config/session_guard.php';require_once __DIR__.'/../../config/config.php';require_role('SAD');
$usuario=current_user();$initials=get_initials($usuario['nombre']);$base=get_base_path();$logout_url=$base.'controllers/AuthController.php?action=logout';$role_label='⚡ Super Administrador';$role_class='role-sad';$avatar_class='avatar-sad';$header_sub='Revisión de solicitud';$_page='SolicitudesRegistro.php';
$idSolicitud=(int)($_GET['id']??0);$solicitud=null;try{$conexion=(new Database())->getConnection();$consulta=$conexion->prepare("SELECT s.*,u.nombre AS nombre_solicitante,u.correo AS correo_solicitante FROM solicitudes_establecimiento s LEFT JOIN usuarios u ON u.id=s.id_usuario_solicitante WHERE s.id=? LIMIT 1");$consulta->execute([$idSolicitud]);$solicitud=$consulta->fetch(PDO::FETCH_ASSOC)?:null;}catch(Throwable $error){error_log('No se pudo cargar solicitud: '.$error->getMessage());}
if($solicitud===null){http_response_code(404);header('Location: SolicitudesRegistro.php');exit;}
$tieneUbicacion=$solicitud['latitud']!==null&&$solicitud['longitud']!==null;$origen=!empty($solicitud['id_usuario_solicitante'])?'ADM registrado':'Solicitud pública';
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RetinAI — Detalle de solicitud</title><link rel="stylesheet" href="<?= $base ?>assets/css/dashboard/dashboard.css"><link rel="stylesheet" href="<?= $base ?>assets/css/dashboard/paneles.css"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"></head><body><?php require_once __DIR__.'/../shared/header.php'; ?><div class="app-shell"><?php require_once __DIR__.'/../shared/sidebar.php'; ?><main class="main-content">
<header class="panel-cabecera"><div><a class="text-muted text-sm" href="SolicitudesRegistro.php">← Solicitudes</a><h1 class="page-title" style="margin-top:8px"><?= htmlspecialchars($solicitud['nombre_centro']) ?></h1><p class="page-sub">Expediente de registro #<?= (int)$solicitud['id'] ?></p></div><span class="etiqueta-estado etiqueta-<?= htmlspecialchars($solicitud['estado']) ?>"><?= htmlspecialchars(ucfirst($solicitud['estado'])) ?></span></header>
<div class="detalle-rejilla"><div class="panel-lista">
<section class="panel-tarjeta"><div class="panel-titulo"><h2>Datos del establecimiento</h2></div><div class="detalle-datos"><?php foreach([['Nombre',$solicitud['nombre_centro']],['RUC',$solicitud['ruc']],['Tipo',ucfirst($solicitud['tipo'])],['Dirección',$solicitud['direccion']],['Origen',$origen],['Fecha',date('d/m/Y H:i',strtotime($solicitud['fecha_solicitud']))]] as $dato): ?><div class="detalle-dato"><span><?= htmlspecialchars($dato[0]) ?></span><strong><?= htmlspecialchars($dato[1]) ?></strong></div><?php endforeach; ?></div></section>
<section class="panel-tarjeta"><div class="panel-titulo"><h2>Titular</h2></div><div class="detalle-datos"><?php foreach([['Nombre',$solicitud['nombres_titular'].' '.$solicitud['apellidos_titular']],['DNI',$solicitud['dni_titular']],['Teléfono',$solicitud['telefono']],['Correo',$solicitud['correo_contacto']]] as $dato): ?><div class="detalle-dato"><span><?= htmlspecialchars($dato[0]) ?></span><strong><?= htmlspecialchars($dato[1]) ?></strong></div><?php endforeach; ?></div></section>
</div><section class="panel-tarjeta"><div class="panel-titulo"><h2>Ubicación</h2></div><?php if($tieneUbicacion): ?><div class="mapa-detalle" id="mapa-solicitud"></div><?php else: ?><div class="estado-vacio">La solicitud no incluye coordenadas confirmadas.</div><?php endif; ?></section></div>
<section class="panel-tarjeta" style="margin-top:18px"><div class="panel-titulo"><h2>Evidencias del establecimiento</h2></div><div class="evidencias-rejilla"><?php $cantidadEvidencias=0;foreach([1,2] as $numero):$contenido=$solicitud['evidencia_'.$numero]??null;$nombre=$solicitud['evidencia_'.$numero.'_nombre']??'';if(!$contenido)continue;$cantidadEvidencias++;$esPdf=str_ends_with(mb_strtolower($nombre),'.pdf'); ?><article><p class="text-sm"><strong><?= htmlspecialchars($nombre?:'Evidencia '.$numero) ?></strong></p><div class="evidencia"><?php if($esPdf): ?><object data="<?= htmlspecialchars($contenido) ?>" type="application/pdf"><a href="<?= htmlspecialchars($contenido) ?>" target="_blank" rel="noopener">Abrir PDF</a></object><?php else: ?><img src="<?= htmlspecialchars($contenido) ?>" alt="Evidencia <?= $numero ?>"><?php endif; ?></div></article><?php endforeach;if($cantidadEvidencias===0): ?><div class="estado-vacio">No se adjuntaron evidencias.</div><?php endif; ?></div></section>
<?php if($solicitud['estado']==='pendiente'): ?><div class="acciones-detalle"><form method="post" action="<?= $base ?>controllers/SolicitudController.php"><input type="hidden" name="action" value="rechazar"><input type="hidden" name="id" value="<?= (int)$solicitud['id'] ?>"><button class="btn btn-danger" type="submit" onclick="return confirm('¿Rechazar esta solicitud?')">Rechazar</button></form><form method="post" action="<?= $base ?>controllers/SolicitudController.php"><input type="hidden" name="action" value="aprobar"><input type="hidden" name="id" value="<?= (int)$solicitud['id'] ?>"><button class="btn btn-primary" type="submit" onclick="return confirm('¿Aprobar esta solicitud?')">Aprobar establecimiento</button></form></div><?php endif; ?>
</main></div><?php if($tieneUbicacion): ?><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const latitud=<?= json_encode((float)$solicitud['latitud']) ?>,longitud=<?= json_encode((float)$solicitud['longitud']) ?>,mapa=L.map('mapa-solicitud').setView([latitud,longitud],16);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapa);L.marker([latitud,longitud]).addTo(mapa).bindPopup(<?= json_encode($solicitud['nombre_centro'],JSON_UNESCAPED_UNICODE) ?>).openPopup();</script><?php endif; ?></body></html>
