<?php
require_once __DIR__.'/../../config/session_guard.php';require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../models/SolicitudModel.php';require_role('SAD');
$usuario=current_user();$initials=get_initials($usuario['nombre']);$base=get_base_path();$logout_url=$base.'controllers/AuthController.php?action=logout';$role_label='Super Administrador';$role_class='role-sad';$avatar_class='avatar-sad';$header_sub='Control global';$_page='SolicitudesRegistro.php';
$solicitudes=[];$cnt_solicitudes_pendientes=0;try{$modelo=new SolicitudModel();$solicitudes=$modelo->getAllSolicitudesConOrigen();$cnt_solicitudes_pendientes=$modelo->countPendientes();}catch(Throwable $error){error_log('No se pudieron listar solicitudes: '.$error->getMessage());}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RetinAI — Solicitudes</title><link rel="stylesheet" href="<?= $base ?>assets/css/dashboard/dashboard.css"><link rel="stylesheet" href="<?= $base ?>assets/css/dashboard/paneles.css"></head><body><?php require_once __DIR__.'/../shared/header.php'; ?><div class="app-shell"><?php require_once __DIR__.'/../shared/sidebar.php'; ?><main class="main-content">
<header class="panel-cabecera"><div><h1 class="page-title">Solicitudes de registro</h1><p class="page-sub">Revisión de solicitudes recibidas.</p></div><button class="boton-informacion" data-ayuda="ayuda-solicitudes" aria-label="Información">i</button></header>
<?php if(isset($_SESSION['solicitud_msg'])): ?><div class="alert-flash alert-ok"><?= htmlspecialchars($_SESSION['solicitud_msg']) ?></div><?php unset($_SESSION['solicitud_msg']);endif; ?>
<section class="panel-tarjeta"><div class="filter-bar"><label class="filter-search" aria-label="Buscar solicitudes"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="2"/><path d="m16.5 16.5 4 4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><input id="filtro-titular" type="search" placeholder="Buscar por titular"></label><select id="filtro-estado"><option value="">Todos los estados</option><option value="pendiente">Pendiente</option><option value="aprobado">Aprobado</option><option value="rechazado">Rechazado</option></select><select id="filtro-origen"><option value="">Todos los orígenes</option><option value="publica">Solicitud pública</option><option value="administrador">ADM registrado</option></select></div>
<div class="table-responsive"><table class="data-table" id="tabla-solicitudes"><thead><tr><th>Centro</th><th>Titular</th><th>Contacto</th><th>Origen</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody><?php if($solicitudes===[]): ?><tr><td colspan="7" class="estado-vacio">No hay solicitudes registradas.</td></tr><?php endif; ?><?php foreach($solicitudes as $solicitud): $titular=$solicitud['nombres_titular'].' '.$solicitud['apellidos_titular'];$origen=!empty($solicitud['id_usuario_solicitante'])?'administrador':'publica'; ?><tr data-fila data-titular="<?= htmlspecialchars(mb_strtolower($titular)) ?>" data-estado="<?= htmlspecialchars($solicitud['estado']) ?>" data-origen="<?= $origen ?>"><td><strong><?= htmlspecialchars($solicitud['nombre_centro']) ?></strong><br><span class="text-muted small">RUC <?= htmlspecialchars($solicitud['ruc']) ?></span></td><td><?= htmlspecialchars($titular) ?><br><span class="text-muted small">DNI <?= htmlspecialchars($solicitud['dni_titular']) ?></span></td><td><?= htmlspecialchars($solicitud['correo_contacto']) ?><br><span class="text-muted small"><?= htmlspecialchars($solicitud['telefono']) ?></span></td><td><?= $origen==='administrador'?'ADM registrado':'Solicitud pública' ?></td><td><?= htmlspecialchars(date('d/m/Y H:i',strtotime($solicitud['fecha_solicitud']))) ?></td><td><span class="etiqueta-estado etiqueta-<?= htmlspecialchars($solicitud['estado']) ?>"><?= htmlspecialchars(ucfirst($solicitud['estado'])) ?></span></td><td><a class="btn btn-primary btn-sm" href="DetalleRegistroEstablecimiento.php?id=<?= (int)$solicitud['id'] ?>">Detalle</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside class="ayuda-flotante" id="ayuda-solicitudes">Use los filtros para encontrar una solicitud. La revisión de ubicación, evidencias y decisión se realiza dentro del detalle.</aside>
</main></div><script src="<?= $base ?>assets/js/paneles.js"></script><script>const filtros=[{selector:'#filtro-titular',campo:'titular'},{selector:'#filtro-estado',campo:'estado'},{selector:'#filtro-origen',campo:'origen'}];filtros.forEach(filtro=>document.querySelector(filtro.selector).addEventListener('input',()=>PanelesRetinAI.filtrarTabla('#tabla-solicitudes',filtros)));</script></body></html>
